name = "astro-personal-website"
pages_build_output_dir = "dist"
compatibility_date = "2023-10-15"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "ViewCountKV"
id = "682c01c937f94375aeec197e89074c10"
