name = "astro-personal-website"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "ViewCountKV"
id = "682c01c937f94375aeec197e89074c10"

[vars]
PNPM_VERSION = "9"
